import { type EquipmentType, type ExerciseDefinition } from '@ferrum/domain';
import { type ApparatusKind, type ImplementKind } from './shapes.ts';
import { type PoseSpec, type View } from './rig.ts';

export type AnchorKind =
  | 'hands'
  | 'near-hand'
  | 'hips'
  | 'ankles'
  | 'near-ankle'
  | 'knees'
  | 'toes'
  | 'chest'
  | 'upper-back';

export interface AnimationSpec {
  readonly view: View;
  readonly apparatus: readonly ApparatusKind[];
  // 'auto' takes the implement from the exercise's equipment type, so one authored pose
  // serves the barbell, dumbbell and machine versions of the same movement.
  readonly implement: ImplementKind | 'auto';
  readonly anchor: AnchorKind;
  // In a bodyweight movement the hands are bolted to a bar and the body is what travels,
  // so the bar path has to be sampled somewhere other than the implement.
  readonly trace?: AnchorKind;
  readonly start: PoseSpec;
  readonly finish: PoseSpec;
  readonly durationMs: number;
  readonly cue: string;
}

const EQUIPMENT_IMPLEMENT: Record<EquipmentType, ImplementKind> = {
  barbell: 'barbell',
  dumbbell: 'dumbbell',
  kettlebell: 'kettlebell',
  machine_stack: 'machine_handle',
  machine_plate_loaded: 'machine_handle',
  smith_machine: 'barbell',
  cable: 'handle',
  bodyweight: 'none',
  band: 'handle',
  sled: 'machine_handle',
  other: 'handle',
};

const STANDING_FEET = {
  foot: [
    [100, 186],
    [100, 186],
  ],
} as const;

// Bases are keyed by movement id, not by pattern: a face pull and a bent-over row share a
// pattern and look nothing alike.
const BY_MOVEMENT: Record<string, AnimationSpec> = {
  horizontal_press: {
    view: 'side',
    apparatus: ['flat_bench'],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [86, 124],
      torso: 0,
      head: 0,
      hand: [114, 108],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 20,
    },
    finish: {
      hip: [86, 124],
      torso: 0,
      head: 0,
      hand: [132, 72],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 20,
    },
    durationMs: 2800,
    cue: 'Bar to the lower chest, elbows tucked, drive back over the shoulder.',
  },
  incline_press: {
    view: 'side',
    apparatus: ['incline_bench'],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [78, 150],
      torso: 40,
      head: 40,
      hand: [104, 106],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [78, 150],
      torso: 40,
      head: 40,
      hand: [124, 60],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 10,
    },
    durationMs: 2800,
    cue: 'Bench at 30-45 degrees, press over the collarbone, not the face.',
  },
  chest_fly: {
    view: 'front',
    apparatus: ['seat'],
    implement: 'auto',
    anchor: 'hands',
    // Both hands move symmetrically, so their midpoint stands still: the path worth
    // drawing is the one a single hand takes.
    trace: 'near-hand',
    start: { hip: [100, 116], torso: 90, hand: [168, 76], elbow: -1, foot: [116, 186], knee: 1 },
    finish: { hip: [100, 116], torso: 90, hand: [120, 78], elbow: -1, foot: [116, 186], knee: 1 },
    durationMs: 2600,
    cue: 'Soft elbows, sweep the hands together, squeeze without shrugging.',
  },
  overhead_press: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: { hip: [100, 112], torso: 90, hand: [110, 76], elbow: -1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 90, hand: [102, 26], elbow: -1, ...STANDING_FEET },
    durationMs: 2800,
    cue: 'Ribs down, press the head through once the bar clears the forehead.',
  },
  lateral_raise: {
    view: 'front',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: { hip: [100, 112], torso: 90, hand: [118, 118], elbow: -1, foot: [112, 186], knee: 1 },
    finish: { hip: [100, 112], torso: 90, hand: [162, 62], elbow: -1, foot: [112, 186], knee: 1 },
    durationMs: 2600,
    cue: 'Lead with the elbow, stop at shoulder height, lower under control.',
  },
  rear_delt_fly: {
    view: 'front',
    apparatus: ['seat'],
    implement: 'auto',
    anchor: 'hands',
    trace: 'near-hand',
    start: { hip: [100, 116], torso: 90, hand: [124, 72], elbow: -1, foot: [116, 186], knee: 1 },
    finish: { hip: [100, 116], torso: 90, hand: [172, 76], elbow: -1, foot: [116, 186], knee: 1 },
    durationMs: 2600,
    cue: 'Open the arms wide, drive from the rear delt, never from the traps.',
  },
  face_pull: {
    view: 'side',
    apparatus: ['cable_high'],
    implement: 'rope',
    anchor: 'hands',
    start: { hip: [100, 112], torso: 88, hand: [150, 62], elbow: -1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 88, hand: [116, 52], elbow: -1, ...STANDING_FEET },
    durationMs: 2600,
    cue: 'Pull to the forehead, elbows high, finish with the knuckles behind the ears.',
  },
  vertical_pull: {
    view: 'side',
    apparatus: ['overhead_bar'],
    implement: 'none',
    anchor: 'hands',
    trace: 'chest',
    start: {
      hip: [100, 136],
      torso: 90,
      hand: [100, 36],
      elbow: -1,
      foot: [74, 182],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 102],
      torso: 90,
      hand: [100, 36],
      elbow: -1,
      foot: [74, 148],
      knee: 1,
      toe: 10,
    },
    durationMs: 3000,
    cue: 'Start from a dead hang, pull the elbows to the ribs, chin over the bar.',
  },
  straight_arm_pulldown: {
    view: 'side',
    apparatus: ['cable_high'],
    implement: 'handle',
    anchor: 'hands',
    start: { hip: [100, 116], torso: 78, hand: [140, 66], elbow: -1, ...STANDING_FEET },
    finish: { hip: [100, 116], torso: 78, hand: [122, 122], elbow: -1, ...STANDING_FEET },
    durationMs: 2600,
    cue: 'Elbows locked soft, sweep the bar to the thighs with the lats.',
  },
  horizontal_row: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [100, 126],
      torso: 34,
      hand: [138, 154],
      elbow: -1,
      foot: [92, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 126],
      torso: 34,
      hand: [124, 118],
      elbow: -1,
      foot: [92, 186],
      knee: 1,
      toe: 10,
    },
    durationMs: 2800,
    cue: 'Hinge to 45 degrees, row to the belly, keep the spine long.',
  },
  squat: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [100, 112],
      torso: 84,
      hand: [92, 60],
      elbow: 1,
      foot: [102, 186],
      knee: -1,
      toe: 10,
    },
    finish: {
      hip: [86, 148],
      torso: 62,
      hand: [96, 104],
      elbow: 1,
      foot: [102, 186],
      knee: -1,
      toe: 10,
    },
    durationMs: 3400,
    cue: 'Break at the hips and knees together, knees track over the toes.',
  },
  lunge: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [100, 118],
      torso: 86,
      foot: [
        [132, 186],
        [70, 180],
      ],
      knee: [-1, -1],
      toe: [10, -10],
    },
    finish: {
      hip: [100, 142],
      torso: 84,
      foot: [
        [132, 186],
        [70, 180],
      ],
      knee: [-1, -1],
      toe: [10, -10],
    },
    durationMs: 3000,
    cue: 'Long stride, drop the back knee straight down, front shin near vertical.',
  },
  hinge: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: {
      hip: [100, 140],
      torso: 24,
      hand: [142, 168],
      elbow: -1,
      foot: [108, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 112],
      torso: 88,
      hand: [104, 122],
      elbow: -1,
      foot: [108, 186],
      knee: 1,
      toe: 10,
    },
    durationMs: 3400,
    cue: 'Push the hips back, bar against the legs, stand tall without leaning back.',
  },
  hip_thrust: {
    view: 'side',
    apparatus: ['flat_bench'],
    implement: 'auto',
    anchor: 'hips',
    start: {
      hip: [100, 156],
      torso: 26,
      hand: [112, 146],
      elbow: 1,
      foot: [70, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 128],
      torso: 3,
      hand: [112, 120],
      elbow: 1,
      foot: [70, 186],
      knee: 1,
      toe: 10,
    },
    durationMs: 2800,
    cue: 'Ribs down, drive through the heels, finish with the shins vertical.',
  },
  back_extension: {
    view: 'side',
    apparatus: ['incline_bench'],
    implement: 'none',
    anchor: 'hands',
    start: {
      hip: [110, 124],
      torso: -30,
      head: -30,
      hand: [150, 142],
      elbow: 1,
      foot: [62, 160],
      knee: -1,
      toe: -30,
    },
    finish: {
      hip: [110, 124],
      torso: 22,
      head: 22,
      hand: [148, 104],
      elbow: 1,
      foot: [62, 160],
      knee: -1,
      toe: -30,
    },
    durationMs: 2800,
    cue: 'Hinge from the hip only, stop when the body is one straight line.',
  },
  knee_extension: {
    view: 'side',
    apparatus: ['seat', 'machine_frame'],
    implement: 'ankle_pad',
    anchor: 'ankles',
    start: {
      hip: [92, 126],
      torso: 82,
      hand: [76, 132],
      elbow: -1,
      foot: [132, 166],
      knee: 1,
      toe: 40,
    },
    finish: {
      hip: [92, 126],
      torso: 82,
      hand: [76, 132],
      elbow: -1,
      foot: [166, 128],
      knee: 1,
      toe: 40,
    },
    durationMs: 2600,
    cue: 'Lock the hips into the seat, extend to straight, pause, lower slowly.',
  },
  knee_flexion: {
    view: 'side',
    apparatus: ['lying_pad', 'machine_frame'],
    implement: 'ankle_pad',
    anchor: 'ankles',
    start: {
      hip: [92, 136],
      torso: 176,
      head: 176,
      hand: [46, 150],
      elbow: 1,
      foot: [166, 134],
      knee: -1,
      toe: 20,
    },
    finish: {
      hip: [92, 136],
      torso: 176,
      head: 176,
      hand: [46, 150],
      elbow: 1,
      foot: [122, 106],
      knee: -1,
      toe: 20,
    },
    durationMs: 2600,
    cue: 'Hips flat on the pad, curl the heels toward the glutes, no hip lift.',
  },
  calf_raise: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: { hip: [100, 118], torso: 90, foot: [100, 190], toe: 0 },
    finish: { hip: [100, 104], torso: 90, foot: [100, 176], toe: -34 },
    durationMs: 2400,
    cue: 'Full stretch at the bottom, rise onto the big toe, hold the top.',
  },
  hip_abduction: {
    view: 'front',
    apparatus: ['seat'],
    implement: 'none',
    anchor: 'knees',
    start: { hip: [100, 126], torso: 90, hand: [124, 134], elbow: -1, foot: [114, 172], knee: -1 },
    finish: { hip: [100, 126], torso: 90, hand: [124, 134], elbow: -1, foot: [150, 166], knee: -1 },
    durationMs: 2400,
    cue: 'Sit tall, push the knees apart, return slowly against the stack.',
  },
  elbow_flexion: {
    view: 'side',
    apparatus: [],
    implement: 'auto',
    anchor: 'hands',
    start: { hip: [100, 112], torso: 90, hand: [106, 120], elbow: -1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 90, hand: [126, 82], elbow: -1, ...STANDING_FEET },
    durationMs: 2400,
    cue: 'Elbows pinned to the ribs, curl with the forearm, no swing.',
  },
  elbow_extension: {
    view: 'side',
    apparatus: ['cable_high'],
    implement: 'rope',
    anchor: 'hands',
    start: { hip: [100, 112], torso: 88, hand: [124, 92], elbow: -1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 88, hand: [122, 132], elbow: -1, ...STANDING_FEET },
    durationMs: 2400,
    cue: 'Upper arm stays still, extend to lockout, resist on the way up.',
  },
  trunk_flexion: {
    view: 'side',
    apparatus: [],
    implement: 'none',
    anchor: 'hands',
    start: {
      hip: [78, 172],
      torso: 14,
      head: 14,
      hand: [118, 158],
      elbow: 1,
      foot: [124, 186],
      knee: -1,
      toe: 20,
    },
    finish: {
      hip: [78, 172],
      torso: 44,
      head: 34,
      hand: [104, 132],
      elbow: 1,
      foot: [124, 186],
      knee: -1,
      toe: 20,
    },
    durationMs: 2400,
    cue: 'Curl the ribs toward the pelvis, the lower back stays down.',
  },
  anti_extension: {
    view: 'side',
    apparatus: [],
    implement: 'none',
    anchor: 'hands',
    trace: 'hips',
    // The "rep" of an isometric is the correction: the start pose sags, the finish is the
    // straight line the lifter is meant to hold.
    start: {
      hip: [106, 170],
      torso: 9,
      head: 9,
      hand: [176, 184],
      elbow: 1,
      foot: [32, 180],
      knee: -1,
      toe: 218,
    },
    finish: {
      hip: [106, 161],
      torso: 14,
      head: 14,
      hand: [176, 184],
      elbow: 1,
      foot: [32, 180],
      knee: -1,
      toe: 218,
    },
    durationMs: 5000,
    cue: 'One line from the ears to the heels, squeeze the glutes, breathe.',
  },
};

// Overrides are merged over the movement base, so a variation only states what differs.
const BY_EXERCISE: Record<string, Partial<AnimationSpec>> = {
  bench_press_smith_machine: { apparatus: ['flat_bench', 'rack'] },
  chest_press_machine: seatedPress(),
  chest_press_machine_plates: seatedPress(),
  pec_deck_machine: { apparatus: ['seat', 'machine_frame'], implement: 'machine_handle' },
  seated_chest_fly_cable: { apparatus: ['seat'], implement: 'handle' },
  // A dumbbell fly is authored from the front like every other fly; the flat bench it is
  // performed on has no silhouette in that view, so the cue carries it instead.
  chest_fly_dumbbell: {
    apparatus: [],
    implement: 'dumbbell',
    cue: 'Lying on a flat bench: soft elbows, open wide, squeeze the hands together.',
  },
  push_up: {
    view: 'side',
    apparatus: [],
    implement: 'none',
    trace: 'chest',
    start: {
      hip: [105, 166],
      torso: 14,
      head: 14,
      hand: [168, 186],
      elbow: 1,
      foot: [33, 178],
      knee: -1,
      toe: 218,
    },
    finish: {
      hip: [108, 152],
      torso: 20,
      head: 20,
      hand: [168, 186],
      elbow: 1,
      foot: [36, 176],
      knee: -1,
      toe: 218,
    },
    cue: 'Hands under the shoulders, body in one line, chest to the floor.',
  },
  dip: {
    view: 'side',
    apparatus: ['dip_bars'],
    implement: 'none',
    anchor: 'hands',
    trace: 'chest',
    start: {
      hip: [100, 124],
      torso: 76,
      hand: [102, 106],
      elbow: -1,
      foot: [72, 174],
      knee: -1,
      toe: -20,
    },
    finish: {
      hip: [100, 100],
      torso: 84,
      hand: [102, 106],
      elbow: -1,
      foot: [76, 150],
      knee: -1,
      toe: -20,
    },
    durationMs: 3000,
    cue: 'Lean forward for the chest, elbows back, stop when the shoulder passes the elbow.',
  },
  seated_shoulder_press_machine: {
    ...seatedOverheadPress(),
    apparatus: ['seat', 'machine_frame'],
    implement: 'machine_handle',
  },
  shoulder_press_machine_plates: {
    ...seatedOverheadPress(),
    apparatus: ['seat', 'machine_frame'],
    implement: 'machine_handle',
  },
  arnold_press_dumbbell: { ...seatedOverheadPress(), apparatus: ['seat'] },
  lateral_raise_machine: { apparatus: [], implement: 'machine_handle' },
  lateral_raise_cable: { apparatus: ['cable_low'], implement: 'handle', view: 'side' },
  rear_delt_fly_machine: { apparatus: ['seat', 'machine_frame'], implement: 'machine_handle' },
  assisted_pull_up_machine: { apparatus: ['overhead_bar', 'machine_frame'] },
  lat_pulldown_cable: latPulldown(),
  close_grip_lat_pulldown_cable: latPulldown(),
  single_arm_lat_pulldown_cable: { ...latPulldown(), implement: 'handle' },
  seated_row_machine: seatedRow(['seat', 'machine_frame'], 'machine_handle'),
  seated_row_cable: seatedRow(['seat', 'cable_low'], 'handle'),
  single_arm_row_cable: seatedRow(['seat', 'cable_low'], 'handle'),
  chest_supported_row_dumbbell: { apparatus: ['incline_bench'], implement: 'dumbbell' },
  t_bar_row: { apparatus: [], implement: 'barbell' },
  inverted_row: {
    view: 'side',
    apparatus: ['rack'],
    implement: 'body_bar',
    anchor: 'hands',
    trace: 'chest',
    start: {
      hip: [96, 154],
      torso: 14,
      head: 14,
      hand: [150, 112],
      elbow: 1,
      foot: [40, 186],
      knee: -1,
      toe: -60,
    },
    finish: {
      hip: [96, 140],
      torso: 16,
      head: 16,
      hand: [150, 112],
      elbow: 1,
      foot: [40, 186],
      knee: -1,
      toe: -60,
    },
    durationMs: 3000,
    cue: 'Heels down, body rigid, pull the chest to the bar.',
  },
  front_squat_barbell: {
    start: {
      hip: [100, 112],
      torso: 86,
      hand: [110, 58],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [90, 146],
      torso: 72,
      hand: [112, 96],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Elbows high, bar on the front delts, stay upright out of the hole.',
  },
  squat_smith_machine: { apparatus: ['rack'] },
  squat_machine: { apparatus: ['machine_frame'], implement: 'shoulder_pad' },
  pendulum_squat_machine: { apparatus: ['machine_frame'], implement: 'shoulder_pad' },
  hack_squat_machine: { apparatus: ['machine_frame'], implement: 'shoulder_pad' },
  goblet_squat_dumbbell: {
    implement: 'dumbbell',
    start: {
      hip: [100, 112],
      torso: 86,
      hand: [118, 74],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [90, 146],
      torso: 70,
      hand: [120, 106],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Bell at the chest, elbows inside the knees, sit straight down.',
  },
  leg_press_machine: {
    view: 'side',
    apparatus: ['leg_press_sled'],
    implement: 'none',
    anchor: 'ankles',
    start: {
      hip: [124, 154],
      torso: 6,
      head: 6,
      hand: [152, 172],
      elbow: 1,
      foot: [92, 120],
      knee: -1,
      toe: 130,
    },
    finish: {
      hip: [124, 154],
      torso: 6,
      head: 6,
      hand: [152, 172],
      elbow: 1,
      foot: [54, 92],
      knee: -1,
      toe: 130,
    },
    durationMs: 3000,
    cue: 'Feet mid-platform, lower until the knees reach 90, never lock hard.',
  },
  calf_press_leg_press: {
    view: 'side',
    apparatus: ['leg_press_sled'],
    implement: 'none',
    anchor: 'ankles',
    trace: 'toes',
    start: {
      hip: [124, 154],
      torso: 6,
      head: 6,
      hand: [152, 172],
      elbow: 1,
      foot: [64, 102],
      knee: -1,
      toe: 170,
    },
    finish: {
      hip: [124, 154],
      torso: 6,
      head: 6,
      hand: [152, 172],
      elbow: 1,
      foot: [52, 90],
      knee: -1,
      toe: 100,
    },
    durationMs: 2400,
    cue: 'Knees soft, press through the ball of the foot, full stretch back.',
  },
  seated_calf_raise: {
    view: 'side',
    apparatus: ['seat'],
    implement: 'shoulder_pad',
    anchor: 'knees',
    start: {
      hip: [96, 126],
      torso: 84,
      hand: [116, 130],
      elbow: -1,
      foot: [134, 188],
      knee: 1,
      toe: 0,
    },
    finish: {
      hip: [96, 126],
      torso: 84,
      hand: [116, 130],
      elbow: -1,
      foot: [134, 176],
      knee: 1,
      toe: -34,
    },
    durationMs: 2400,
    cue: 'Pad on the lower thigh, heels below the platform, push the knees up.',
  },
  calf_extension_machine: {
    apparatus: ['machine_frame'],
    implement: 'shoulder_pad',
    anchor: 'upper-back',
  },
  glute_kickback_cable: {
    view: 'side',
    apparatus: ['cable_low'],
    implement: 'ankle_pad',
    anchor: 'near-ankle',
    start: {
      hip: [100, 124],
      torso: 52,
      hand: [140, 96],
      elbow: -1,
      foot: [
        [104, 186],
        [96, 186],
      ],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 124],
      torso: 52,
      hand: [140, 96],
      elbow: -1,
      foot: [
        [54, 156],
        [96, 186],
      ],
      knee: 1,
      toe: 10,
    },
    durationMs: 2600,
    cue: 'Hinge, then push the heel back and up from the glute alone.',
  },
  hip_thrust_machine: { apparatus: ['seat'], implement: 'hip_pad' },
  hanging_leg_raise: {
    view: 'side',
    apparatus: ['overhead_bar'],
    implement: 'none',
    anchor: 'hands',
    trace: 'ankles',
    start: {
      hip: [100, 136],
      torso: 90,
      hand: [100, 36],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 136],
      torso: 90,
      hand: [100, 36],
      elbow: -1,
      foot: [146, 122],
      knee: 1,
      toe: 40,
    },
    durationMs: 3000,
    cue: 'Hang still, curl the pelvis up, lower without swinging.',
  },
  cable_crunch: {
    view: 'side',
    apparatus: ['cable_high'],
    implement: 'rope',
    anchor: 'hands',
    start: {
      hip: [96, 148],
      torso: 84,
      head: 84,
      hand: [120, 66],
      elbow: -1,
      foot: [
        [120, 186],
        [78, 186],
      ],
      knee: -1,
      toe: [30, 30],
    },
    finish: {
      hip: [96, 148],
      torso: 46,
      head: 40,
      hand: [120, 108],
      elbow: -1,
      foot: [
        [120, 186],
        [78, 186],
      ],
      knee: -1,
      toe: [30, 30],
    },
    durationMs: 2600,
    cue: 'Kneel under the rope, crunch the ribs down, hips stay where they are.',
  },
  ab_crunch_machine: {
    view: 'side',
    apparatus: ['seat', 'machine_frame'],
    implement: 'machine_handle',
    anchor: 'hands',
    start: {
      hip: [92, 128],
      torso: 86,
      head: 86,
      hand: [112, 66],
      elbow: -1,
      foot: [126, 186],
      knee: 1,
      toe: 20,
    },
    finish: {
      hip: [92, 128],
      torso: 54,
      head: 46,
      hand: [122, 104],
      elbow: -1,
      foot: [126, 186],
      knee: 1,
      toe: 20,
    },
    cue: 'Grip the pads, curl the ribs toward the pelvis, hips stay in the seat.',
  },
  side_plank: {
    view: 'side',
    apparatus: [],
    implement: 'none',
    anchor: 'hands',
    trace: 'hips',
    start: {
      hip: [106, 170],
      torso: 9,
      head: 9,
      hand: [
        [176, 184],
        [140, 104],
      ],
      elbow: [1, -1],
      foot: [
        [32, 180],
        [34, 178],
      ],
      knee: [-1, -1],
      toe: [218, 218],
    },
    finish: {
      hip: [106, 161],
      torso: 14,
      head: 14,
      hand: [
        [176, 184],
        [136, 92],
      ],
      elbow: [1, -1],
      foot: [
        [32, 180],
        [34, 178],
      ],
      knee: [-1, -1],
      toe: [218, 218],
    },
    durationMs: 5000,
    cue: 'Stack the hips, drive the bottom elbow down, hold without sagging.',
  },
  preacher_curl_machine: {
    apparatus: ['preacher_pad'],
    start: {
      hip: [86, 128],
      torso: 66,
      hand: [154, 108],
      elbow: -1,
      foot: [70, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [86, 128],
      torso: 66,
      hand: [126, 74],
      elbow: -1,
      foot: [70, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Upper arms flat on the pad, full stretch at the bottom.',
  },
  bicep_curl_cable: { apparatus: ['cable_low'], implement: 'handle' },
  incline_curl_dumbbell: {
    apparatus: ['incline_bench'],
    implement: 'dumbbell',
    start: {
      hip: [78, 150],
      torso: 40,
      head: 40,
      hand: [122, 158],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [78, 150],
      torso: 40,
      head: 40,
      hand: [136, 108],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 10,
    },
    cue: 'Let the arms hang behind the body, curl without moving the shoulder.',
  },
  concentration_curl_dumbbell: {
    apparatus: ['seat'],
    implement: 'dumbbell',
    start: {
      hip: [92, 126],
      torso: 56,
      hand: [
        [146, 150],
        [104, 140],
      ],
      elbow: [-1, -1],
      foot: [
        [126, 186],
        [70, 186],
      ],
      knee: [1, 1],
      toe: [20, 20],
    },
    finish: {
      hip: [92, 126],
      torso: 56,
      hand: [
        [132, 108],
        [104, 140],
      ],
      elbow: [-1, -1],
      foot: [
        [126, 186],
        [70, 186],
      ],
      knee: [1, 1],
      toe: [20, 20],
    },
    cue: 'Elbow braced on the inner thigh, curl to the shoulder, squeeze.',
  },
  skullcrusher_barbell: {
    apparatus: ['flat_bench'],
    implement: 'barbell',
    view: 'side',
    start: {
      hip: [86, 124],
      torso: 0,
      head: 0,
      hand: [150, 92],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 20,
    },
    finish: {
      hip: [86, 124],
      torso: 0,
      head: 0,
      hand: [134, 66],
      elbow: -1,
      foot: [58, 184],
      knee: 1,
      toe: 20,
    },
    cue: 'Elbows point at the ceiling, lower behind the head, extend to lockout.',
  },
  overhead_triceps_extension_cable: {
    apparatus: ['cable_high'],
    implement: 'rope',
    start: { hip: [100, 112], torso: 88, hand: [150, 70], elbow: 1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 88, hand: [116, 30], elbow: 1, ...STANDING_FEET },
    cue: 'Upper arms beside the ears, only the elbow moves.',
  },
  overhead_triceps_extension_dumbbell: {
    apparatus: [],
    implement: 'dumbbell',
    start: { hip: [100, 112], torso: 88, hand: [78, 62], elbow: 1, ...STANDING_FEET },
    finish: { hip: [100, 112], torso: 88, hand: [104, 26], elbow: 1, ...STANDING_FEET },
    cue: 'Bell behind the head, elbows narrow, press straight up.',
  },
  triceps_extension_machine: { apparatus: ['seat', 'machine_frame'], implement: 'machine_handle' },
  triceps_pushdown: { apparatus: ['cable_high'], implement: 'rope' },
  lying_leg_curl_machine: {},
  seated_leg_curl_machine: {
    apparatus: ['seat', 'machine_frame'],
    implement: 'ankle_pad',
    anchor: 'ankles',
    view: 'side',
    start: {
      hip: [92, 126],
      torso: 82,
      hand: [76, 132],
      elbow: -1,
      foot: [162, 132],
      knee: 1,
      toe: 40,
    },
    finish: {
      hip: [92, 126],
      torso: 82,
      hand: [76, 132],
      elbow: -1,
      foot: [126, 168],
      knee: 1,
      toe: 40,
    },
    cue: 'Pad above the ankles, curl the heels under the seat.',
  },
  hip_abduction_machine: {},
  walking_lunge_dumbbell: { implement: 'dumbbell' },
  bulgarian_split_squat_dumbbell: {
    implement: 'dumbbell',
    apparatus: ['flat_bench'],
    start: {
      hip: [104, 118],
      torso: 84,
      foot: [
        [136, 186],
        [66, 128],
      ],
      knee: [1, 1],
      toe: [10, -40],
    },
    finish: {
      hip: [104, 146],
      torso: 78,
      foot: [
        [136, 186],
        [66, 128],
      ],
      knee: [1, 1],
      toe: [10, -40],
    },
    cue: 'Rear foot on the bench, weight through the front heel.',
  },
  romanian_deadlift_barbell: romanianDeadlift(),
  romanian_deadlift_dumbbell: { ...romanianDeadlift(), implement: 'dumbbell' },
  dumbbell_row: {
    implement: 'dumbbell',
    apparatus: ['flat_bench'],
    start: {
      hip: [96, 128],
      torso: 26,
      hand: [
        [142, 158],
        [122, 140],
      ],
      elbow: [-1, -1],
      foot: [
        [74, 186],
        [86, 186],
      ],
      knee: [1, 1],
      toe: [10, 10],
    },
    finish: {
      hip: [96, 128],
      torso: 26,
      hand: [
        [132, 124],
        [122, 140],
      ],
      elbow: [-1, -1],
      foot: [
        [74, 186],
        [86, 186],
      ],
      knee: [1, 1],
      toe: [10, 10],
    },
    cue: 'One hand braced, row the bell to the hip, no torso rotation.',
  },
};

function seatedOverheadPress(): Partial<AnimationSpec> {
  return {
    view: 'side',
    anchor: 'hands',
    start: {
      hip: [92, 126],
      torso: 86,
      hand: [112, 88],
      elbow: -1,
      foot: [124, 186],
      knee: 1,
      toe: 20,
    },
    finish: {
      hip: [92, 126],
      torso: 86,
      hand: [100, 36],
      elbow: -1,
      foot: [124, 186],
      knee: 1,
      toe: 20,
    },
    cue: 'Back against the pad, press straight overhead, elbows finish under the wrists.',
  };
}

function seatedPress(): Partial<AnimationSpec> {
  return {
    view: 'side',
    apparatus: ['seat', 'machine_frame'],
    implement: 'machine_handle',
    anchor: 'hands',
    start: {
      hip: [92, 126],
      torso: 84,
      hand: [112, 88],
      elbow: -1,
      foot: [122, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [92, 126],
      torso: 84,
      hand: [156, 84],
      elbow: -1,
      foot: [122, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Back flat on the pad, press away from the chest, control the return.',
  };
}

function latPulldown(): Partial<AnimationSpec> {
  return {
    view: 'side',
    apparatus: ['seat', 'cable_high'],
    implement: 'lat_bar',
    anchor: 'hands',
    start: {
      hip: [92, 126],
      torso: 78,
      hand: [128, 46],
      elbow: -1,
      foot: [122, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [92, 126],
      torso: 74,
      hand: [118, 92],
      elbow: -1,
      foot: [122, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Chest up, pull the bar to the collarbone, elbows down and back.',
  };
}

function seatedRow(
  apparatus: readonly ApparatusKind[],
  implement: ImplementKind
): Partial<AnimationSpec> {
  return {
    view: 'side',
    apparatus,
    implement,
    anchor: 'hands',
    start: {
      hip: [88, 128],
      torso: 66,
      hand: [162, 122],
      elbow: -1,
      foot: [140, 176],
      knee: 1,
      toe: 30,
    },
    finish: {
      hip: [88, 128],
      torso: 88,
      hand: [116, 118],
      elbow: -1,
      foot: [140, 176],
      knee: 1,
      toe: 30,
    },
    cue: 'Row to the navel, shoulder blades back, torso barely moves.',
  };
}

function romanianDeadlift(): Partial<AnimationSpec> {
  return {
    start: {
      hip: [102, 128],
      torso: 28,
      hand: [140, 160],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    finish: {
      hip: [100, 112],
      torso: 88,
      hand: [104, 122],
      elbow: -1,
      foot: [102, 186],
      knee: 1,
      toe: 10,
    },
    cue: 'Knees soft and fixed, hips travel back, stop at the stretch.',
  };
}

export function resolveAnimation(definition: ExerciseDefinition): AnimationSpec {
  // No silent fallback: a movement family added to the library without a pose must fail
  // loudly in the coverage test, not quietly render somebody else's exercise.
  const base = BY_MOVEMENT[definition.movementId];
  if (base === undefined) {
    throw new Error(`No base animation for movement "${definition.movementId}"`);
  }
  const merged: AnimationSpec = { ...base, ...BY_EXERCISE[definition.id] };
  return merged.implement === 'auto'
    ? { ...merged, implement: EQUIPMENT_IMPLEMENT[definition.equipmentType] }
    : merged;
}

export function animationMovementIds(): readonly string[] {
  return Object.keys(BY_MOVEMENT);
}
